### PR TITLE
CLDF creation via cldfbench

### PR DESCRIPTION
**Pull request by J22Melody**
Similarly as did in https://github.com/cldf-datasets/segbo, use Git submodule to import the raw data and then convert it into 4  tables.

- `values.csv`: all the tones with their inventory foreign keys, all the additional fields from `Tonogenesis - Database.csv`
- `contributions.csv`: all the inventories from `Tonogenesis - Index.csv`
- `languages.csv`: all the languages with all the joined fields from `languoid.csv`
- `parameters.csv`: nothing really, should we move some fields in `values.csv` here? @bambooforest 

@bambooforest a problem is that some languages are not found by their `Glottocode`. For `thai1261?` should we remove the trailing question mark?

```
cldf/values.csv:69 Key `pwon1236` not found in table languages.csv
cldf/values.csv:70 Key `pwon1237` not found in table languages.csv
cldf/values.csv:71 Key `pwon1238` not found in table languages.csv
cldf/values.csv:72 Key `pwon1239` not found in table languages.csv
cldf/values.csv:73 Key `pwon1240` not found in table languages.csv
cldf/values.csv:80 Key `hmon1339` not found in table languages.csv
cldf/values.csv:81 Key `hmon1340` not found in table languages.csv
cldf/values.csv:82 Key `hmon1341` not found in table languages.csv
cldf/values.csv:83 Key `hmon1342` not found in table languages.csv
cldf/values.csv:129 Key `extr1246` not found in table languages.csv
cldf/values.csv:150 Key `thai1261?` not found in table languages.csv
cldf/values.csv:151 Key `thai1261?` not found in table languages.csv
cldf/values.csv:152 Key `thai1261?` not found in table languages.csv
cldf/values.csv:153 Key `thai1261?` not found in table languages.csv
cldf/values.csv:154 Key `thai1261?` not found in table languages.csv
cldf/values.csv:155 Key `thai1261?` not found in table languages.csv
cldf/values.csv:204 Key `can1236` not found in table languages.csv
cldf/values.csv:205 Key `can1236` not found in table languages.csv
cldf/values.csv:206 Key `can1236` not found in table languages.csv
cldf/values.csv:207 Key `can1236` not found in table languages.csv
cldf/values.csv:208 Key `can1236` not found in table languages.csv
cldf/values.csv:209 Key `can1236` not found in table languages.csv
```

### CODE REVIEW

**Comment by bambooforest** [comment]
@J22Melody -- adding in line comments for the code review. I need to ask the other editors about the glottocodes and will get back to you.

**Comment by bambooforest** [comment]
@J22Melody -- for the values.csv do we need both an `ID` and a `Parameter_ID` field? they are the same values.

**Comment by J22Melody** [comment]
> @J22Melody -- for the values.csv do we need both an `ID` and a `Parameter_ID` field? they are the same values.

It is what I am not very sure about. 

First by default the CLDF formats requires a ParameterTable thus there is a foreign key in ValueTable called `Parameter_ID`. In   Phoible the ParameterTable stores parameters for all the phonemes, but actually in all the databases I am converting, there are not those parameters. Should we just drop the ParameterTable?

Currently I just keep it in a minimal way, but maybe it's not the correct way ... I should probably generate a id for each tone/phoneme and make it the `Parameter_ID`. What do you think?

**Comment by J22Melody** [comment]
> @J22Melody -- adding in line comments for the code review. I need to ask the other editors about the glottocodes and will get back to you.

Thanks! Same issue here https://github.com/J22Melody/semphon/issues/1 for Semphon.

**Comment by bambooforest** [comment]
@J22Melody -- can you resend the invite for semphon? I don't see parentheses in the metadata for Glottocodes, so I assume some are (now) invalid glottocodes?

**Comment by bambooforest** [comment]
@J22Melody -- note that the Glottocodes have been updated (parentheses removed; comments of why they were noted in a new column). Can we rerun the pipeline, so as to remove these warnings and get the "correct" glottocodes in? Thanks!

**Comment by xrotwang** [comment]
Finally back at work - sorry for delaying this.

I'm not quite clear what exactly `tonodb` is "measuring" - is it the existence and types of tones in languages? If so - can tones be compared across languages? Right now the `values.ID == values.Parameter_ID` is just a symptom of the fact that parameters seem to be language specific. If the only comparative concept here is "has tones", then we might be better off modelling this with just one parameter "Tone" - and the set of values of one language for this parameter representing the tone inventory?

**Comment by bambooforest** [comment]
@xrotwang -- it documents the tones in the context in which they arose (their genesis). See email. :)

**Comment by xrotwang** [comment]
Ok, understood. I think in this case, I'd just use one - somewhat dummy - parameter "Tone", and shove all columns of the spreadsheet into `ValueTable`. In the `clld` app data model we have `Unit`s - to model language units, e.g. affixes or markers - and associated `UnitParameter`s. But it's not yet clear how to support this in CLDF - see the discussion at https://github.com/cldf/cldf/issues/98#issuecomment-635898902

**Comment by J22Melody** [comment]
> @J22Melody -- can you resend the invite for semphon? I don't see parentheses in the metadata for Glottocodes, so I assume some are (now) invalid glottocodes?

I just transferred its ownship to @xrotwang , let us move it under https://github.com/cldf-datasets like we did for Segbo, then you both can see it.

**Comment by J22Melody** [comment]
> @J22Melody -- note that the Glottocodes have been updated (parentheses removed; comments of why they were noted in a new column). Can we rerun the pipeline, so as to remove these warnings and get the "correct" glottocodes in? Thanks!

Where did you update the Glottocodes? I cannot find update in https://github.com/uzling/tono_db.

**Comment by bambooforest** [comment]
@J22Melody -- you would have to pull the recent updates from the google sheets to the repo.

**Comment by xrotwang** [comment]
@J22Melody We have a python library to help getting data from google sheets: https://collabutils.readthedocs.io/en/latest/googlesheets.html
May be useful here. We use it in other cldfbench-enabled repos in the download command, like so: 
https://github.com/tupian-language-resources/tuled/blob/92a96f947a1986ccd925fe284579b6de68748939/lexibank_tuled.py#L66-L67

**Comment by J22Melody** [comment]
> @J22Melody -- you would have to pull the recent updates from the google sheets to the repo.

Done with that, now we left with one Glottocode not found:

```cldf/values.csv:205 Key `can1236` not found in table languages.csv```

**Comment by bambooforest** [comment]
@J22Melody -- great catch. I updated this to cant1236 in the spreadsheet. Thanks!

**Comment by bambooforest** [comment]
@xrotwang -- do you guys have a preferred workflow. for example, we use google sheets for the data entry for most of these cldf datasets, then dump the CSV to their GitHub repos and do the merging, checking, etc. now we read the git repos as submodules and create the CLDF. I guess we could go the other way around and read the sheets directly, create the cldf, and then dump back to the general repo.

**Comment by xrotwang** [comment]
Hm. Sounds as if you could also retire the general repo - or create the CLDF in the general repo and remove the cldf-datasets one?

**Comment by bambooforest** [comment]
honestly, don't care too much where this stuff lives, but not sure if you want a bunch of visualizations and preliminary analyses in the cldd-datasets repos?

**Comment by xrotwang** [comment]
The only issue I'd have with such additional stuff would be repo size. I.e. if there's a risk of going over Zenodo's 2GB limit for deposits, that would be bad. Otherwise I'd say such additional context is good!

**Comment by bambooforest** [comment]
ok. perhaps we can try it then, @J22Melody ? apologies for not being then foresightful! it would mean updating the CLDF conversion in this repo to read directly from the spreadsheets and then we just close the the other tono_dbrepo. I would then just migrate the short report here.

**Comment by J22Melody** [comment]
> @J22Melody We have a python library to help getting data from google sheets: https://collabutils.readthedocs.io/en/latest/googlesheets.html
> May be useful here. We use it in other cldfbench-enabled repos in the download command, like so:
> https://github.com/tupian-language-resources/tuled/blob/92a96f947a1986ccd925fe284579b6de68748939/lexibank_tuled.py#L66-L67

@xrotwang I tried to follow the way you did (using the pytular library) but it asked me the "Path to Google API key file:", does it mean that if I want to fetch Google Spreadsheet in Python, I must have a local Google API key file by myself? (If so I feel like this way is a bit cumbersome and the code cannot rerun elsewhere.)

**Comment by xrotwang** [comment]
@J22Melody yes, you'd have to create a service account, see https://docs.gspread.org/en/latest/oauth2.html#for-bots-using-service-account

**Comment by bambooforest** [comment]
@J22Melody , no pressure to create an account -- we can do it the original way, if you prefer.

**Comment by J22Melody** [comment]
> @J22Melody , no pressure to create an account -- we can do it the original way, if you prefer.

OK I have quickly fixed it in the original way, now tonodb is good I believe.

**Comment by bambooforest** [comment]
@J22Melody looks good to me except two things:

- as I noted, the citation shouldn't be (or just be) to the Glottolog, as I understand things, the database collection work for TonoDB is: "Lilja Saeboe, Alena Witzlack, Eitan Grossman, & Steven Moran. 2021. TonoDB: a database of tonogenesis events."

- Contributor in contributions.csv is always blank -- if we're talking about who extracted the data, then this should Lilja Saeboe throughout as Contibutor -- if it's easier, we can add this to the google sheet and propagate it through

@xrotwang -- anything else wrt to the CLDF data? otherwise, I think we can merge after these two issues are resolved

**Comment by J22Melody** [comment]
> @J22Melody looks good to me except two things:
> 
> * as I noted, the citation shouldn't be (or just be) to the Glottolog, as I understand things, the database collection work for TonoDB is: "Lilja Saeboe, Alena Witzlack, Eitan Grossman, & Steven Moran. 2021. TonoDB: a database of tonogenesis events."
> * Contributor in contributions.csv is always blank -- if we're talking about who extracted the data, then this should Lilja Saeboe throughout as Contibutor -- if it's easier, we can add this to the google sheet and propagate it through
> 
> @xrotwang -- anything else wrt to the CLDF data? otherwise, I think we can merge after these two issues are resolved

Resolved by adding `Citation` and `Contributor` in contributions.csv.

**Pull request merged**
